# This is a basic workflow to help you get started with Actions

name: Build and Publish Pages

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ development ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch: 

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  compile:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout the Development branch
        uses: actions/checkout@v2
        with:
          ref: development

      # Runs a single command using the runners shell
      - name: Compile the website into static files
        uses: OrangeLabs-moe/gradle-actions@v5.0-openjdk-15
        with:
          args: clean jsBrowserDistribution

      - name: Upload generated pages
        if: ${{ success() }}
        uses: actions/upload-artifact@v2
        with:
          name: website-files
          path: |
            build/distributions/index.html
            build/distributions/renegademaster-website.js
      
      - name: Checkout main branch
        
  upload:
    runs-on: ubuntu-latest
    steps:      
      - name: Checkout the main branch
        uses: actions/checkout@v2
        with:
          ref: main
      
      - name: Download generated pages
        uses: actions/download-artifact@v2
        with:
          name: website-files
          path: ./
      
      - name: Investigate
        run: cat ./*
        
